[package]
name = "jman-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.50"
dirs-next = "2.0.0"
miniserde = "0.1.43"

[target.'cfg(windows)'.dependencies]
junction = "1.3.0"
winreg = "0.55.0"
